[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.flash_mode = dio

monitor_speed = 115200

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_compat_mode = strict
lib_ldf_mode = deep+
lib_ignore = WebServer

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.6
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    mathieucarbou/AsyncTCP @ ^3.3.2
    adafruit/Adafruit NeoPixel @ ^1.12.0
